<b>Задача про светафор<b>

In [2]:
import numpy as np

In [3]:
#data set

#входные данные
streetlights = np.array([
    [1, 0, 1],
    [0, 1, 1],
    [0, 0, 1],
    [1, 1, 1],
    [0, 1, 1],
    [1, 0, 1]
])

#выходные данные
walk_vs_stop = np.array([[0], [1], [0], [1], [1], [0] ])

weights = np.array([0.5, 0.48, -0.7]) #3 признака - 3 весовых коэфецента
alpha = 0.1

In [4]:
input = streetlights[0] # 101
goal_pred = walk_vs_stop[0] # 0 - стоять

for iter in range(20):
    pred = input.dot(weights) #скалярное произведение 
    error = (pred - goal_pred) ** 2
    delta = pred - goal_pred
    weights -= alpha * (input * delta)
    
    print(f'Error: {error} Prediction: {pred}')

Error: [0.04] Prediction: -0.19999999999999996
Error: [0.0256] Prediction: -0.15999999999999992
Error: [0.016384] Prediction: -0.1279999999999999
Error: [0.01048576] Prediction: -0.10239999999999982
Error: [0.00671089] Prediction: -0.08191999999999977
Error: [0.00429497] Prediction: -0.06553599999999982
Error: [0.00274878] Prediction: -0.05242879999999994
Error: [0.00175922] Prediction: -0.04194304000000004
Error: [0.0011259] Prediction: -0.03355443200000008
Error: [0.00072058] Prediction: -0.02684354560000002
Error: [0.00046117] Prediction: -0.021474836479999926
Error: [0.00029515] Prediction: -0.01717986918399994
Error: [0.00018889] Prediction: -0.013743895347199997
Error: [0.00012089] Prediction: -0.010995116277759953
Error: [7.73712525e-05] Prediction: -0.008796093022207963
Error: [4.95176016e-05] Prediction: -0.007036874417766459
Error: [3.1691265e-05] Prediction: -0.0056294995342132115
Error: [2.02824096e-05] Prediction: -0.004503599627370569
Error: [1.29807421e-05] Prediction: -

<b>Обучение нейронки на полном наборе данных<b>

In [5]:
for iteration in range(40):
    error_for_all_lights = 0
    for row_index in range(len(walk_vs_stop)):
        input = streetlights[row_index]
        goal_predition = walk_vs_stop[row_index]
        
        predict = input.dot(weights)
        
        error = (predict - goal_predition) ** 2
        error_for_all_lights += error
        
        delta = predict - goal_predition
        weights -= alpha * (input * delta)
        
        print(f'Prediction: {predict}')
    
    print(f'Error: {error_for_all_lights}')
    print(f'Weights: {weights}\n')

Prediction: -0.0023058430092137705
Prediction: -0.1209223372036855
Prediction: -0.4888301034833169
Prediction: 0.7512228033816979
Prediction: 0.20190057990904375
Prediction: 0.2886959509940853
Error: [2.2776252]
Weights: [ 0.59508579  0.6967799  -0.36412903]

Prediction: 0.23095676079526822
Prediction: 0.3095551927482997
Prediction: -0.31818022191782463
Prediction: 1.0514522876696315
Prediction: 0.46917171885649595
Prediction: 0.3284202821335913
Error: [1.02357959]
Weights: [ 0.53400285  0.81376198 -0.27126663]

Prediction: 0.26273622570687305
Prediction: 0.5162217243011503
Prediction: -0.24916242359281637
Prediction: 1.1456228535284017
Prediction: 0.6087690510945215
Prediction: 0.2934815746795325
Error: [0.62555276]
Weights: [ 0.46381879  0.88670061 -0.22903353]

Prediction: 0.23478525974362602
Prediction: 0.6341885574333014
Prediction: -0.21593091088147304
Prediction: 1.1692841999678323
Prediction: 0.6950870970412221
Prediction: 0.24263689344202927
Error: [0.41606997]
Weights: [ 0.39

<b>Объединение нейронных сетей в стек - добавление скрытых слоев 
    Первая глубокая нейросеть<b>

In [6]:
np.random.seed(1)

In [7]:
def relu(x):
    return (x > 0) * x

def relu2deriv(output):
    return output > 0

In [8]:
alpha = 0.2
hidden_size = 4 #количество нейронов (узлов) в скрытом слое

streetlights_n = np.array([
    [1, 0, 1],
    [0, 1, 1],
    [0, 0, 1],
    [1, 1, 1,]
])

walk_vs_stop_n = np.array([[1, 1, 0, 0]]).T

weights_0_1 = 2 * np.random.random((3, hidden_size)) - 1 #преобразует отрицаельные числа в 0
weights_1_2 = 2 * np.random.random((hidden_size, 1)) - 1




In [9]:
for iteration in range(60):
    layer_2_error = 0
    for i in range(len(streetlights_n)):
        
        layer_0 = streetlights_n[i:i+1] #input
        layer_1 = relu(np.dot(layer_0, weights_0_1)) #hidden 
        layer_2 = np.dot(layer_1, weights_1_2) #output - prediction
        
        layer_2_error += np.sum((layer_2 - walk_vs_stop_n[i:i+1]) ** 2)
        
        #тот самый back propagation 
        layer_2_delta = (walk_vs_stop_n[i:i+1] - layer_2)
        layer_1_delta = layer_2_delta.dot(weights_1_2.T) * relu2deriv(layer_1)
        
        weights_1_2 += alpha * layer_1.T.dot(layer_2_delta)
        weights_0_1 += alpha * layer_0.T.dot(layer_1_delta)
        
    if(iteration % 10 == 9):
        print(f'Iter: {iteration} - Error: {layer_2_error}\n')
        
        
        

Iter: 9 - Error: 0.6342311598444467

Iter: 19 - Error: 0.35838407676317513

Iter: 29 - Error: 0.0830183113303298

Iter: 39 - Error: 0.006467054957103705

Iter: 49 - Error: 0.0003292669000750734

Iter: 59 - Error: 1.5055622665134859e-05



In [10]:
test = np.array([[0,1,1]])
l_0 = test[0:1]
l_1 = relu(np.dot(l_0, weights_0_1))
l_2 = np.dot(l_1, weights_1_2)
l_2[0][0]

0.9985532569162426

<b>Все то же самое только одна иттерация - подробно<b>

In [16]:
hidden_size = 3 #количество нейронов (узлов) в скрытом слое

lights = np.array([
    [1, 0, 1], # входные данные
    [0, 1, 1],
    [0, 0, 1],
    [1, 1, 1,]
])

walk_stop = np.array([[1, 1, 0, 0]]).T

weights_0_1 = 2 * np.random.random((3, hidden_size)) - 1 #преобразует отрицаельные числа в 0
weights_1_2 = 2 * np.random.random((hidden_size, 1)) - 1

layer_0 = lights[0:1]
print(layer_0)
layer_1 = np.dot(layer_0, weights_0_1)
print(weights_0_1)
print(len(layer_1[0]))
layer_1 = relu(layer_1)
layer_2 = np.dot(layer_1, weights_1_2)
print(layer_2)

error = (layer_2 - walk_stop[0:1]) ** 2

# вычисление delta 
layer_2_delta = (layer_2 - walk_stop[0:1])

# обратное распространение из layer_2 в layer_1
layer_1_delta = layer_2_delta.dot(weights_1_2.T)
layer_1_delta *= relu2deriv(layer_1)

weight_delta_1_2 = layer_1.T.dot(layer_2_delta) # градиентный спуск - производные
weight_delta_0_1 = layer_0.T.dot(layer_1_delta)

#изменение исходных весов
weights_1_2 -= alpha * weight_delta_1_2
weights_0_1 -= alpha * weight_delta_0_1



[[1 0 1]]
[[ 0.85501716 -0.30446828  0.50162421]
 [ 0.45199597  0.76661218  0.24734441]
 [ 0.50188487 -0.30220332 -0.46014422]]
3
[[1.11292075]]
