In [23]:
import numpy as np

<b>#1 Градиентный спуск для нескольких входных значений<b>

In [28]:
def neural_network(input, weights):
    pred = w_sum(input, weights)
    return pred

def w_sum(a, b):
    assert(len(a) == len(b))
    output = 0
    
    for i in range(len(a)):
        output+= a[i] * b[i]
    
    return output

def ele_mul(number, vector):
    output = [0] * 3
    
    assert(len(output) == len(vector))
    
    for i in range(len(output)):
        output[i] = number * vector[i]
    
    return output

In [7]:
weights = [0.1, 0.2, -0.1]

toes = [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65, 0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]

win_or_lose_binary = [1, 1, 0, 1]

true = win_or_lose_binary[0]
input = [toes[0], wlrec[0], nfans[0]] #вектор

pred = neural_network(input, weights) #скаляр

error = (pred - true) ** 2

delta = pred - true

weight_deltas = ele_mul(delta, input)
#print(weight_deltas)

alpha = 0.01

for i in range(len(weights)):
    weights[i] -= alpha * weight_deltas[i]
print(f'Weights: {weights}')
print(f'Weights Deltas: {weight_deltas}')

#print(neural_network(input, weights))

Weights: [0.1119, 0.20091, -0.09832]
Weights Deltas: [-1.189999999999999, -0.09099999999999994, -0.16799999999999987]
0.9637574999999999


<b>#2 Градиентный спуск для нескольких входных значений в нескольких иттерацях<b>

In [42]:
weights = [0.1, 0.2, -0.1]

toes = [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65, 0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]

win_or_lose_binary = [1, 1, 0, 1]

alpha = 0.01

true = win_or_lose_binary[0]
input = [toes[0], wlrec[0], nfans[0]]

In [45]:
for iter in range(3): #28 итераций - идеальное обучение 
    
    pred = neural_network(input, weights)
    
    error = (pred - true) ** 2
    delta = pred - true
    
    weights_deltas = ele_mul(delta, input)
    
    print(f'Iteration: {iter}')
    print(f'Prediction: {pred}')
    print(f'Error: {error}')
    print(f'Delta: {delta}')
    print(f'Weights: {weights}')
    print(f'Delta Weights: \n{weights_deltas}')
    print("--------------------------" + "\n")
    
    for i in range(len(weights)):
        weights[i] -= alpha * weights_deltas[i]

Iteration: 0
Prediction: 1.0
Error: 0.0
Delta: 0.0
Weights: [0.11605667060212514, 0.2012278630460449, -0.09773317591499411]
Delta Weights: 
[0.0, 0.0, 0.0]
--------------------------

Iteration: 1
Prediction: 1.0
Error: 0.0
Delta: 0.0
Weights: [0.11605667060212514, 0.2012278630460449, -0.09773317591499411]
Delta Weights: 
[0.0, 0.0, 0.0]
--------------------------

Iteration: 2
Prediction: 1.0
Error: 0.0
Delta: 0.0
Weights: [0.11605667060212514, 0.2012278630460449, -0.09773317591499411]
Delta Weights: 
[0.0, 0.0, 0.0]
--------------------------



<b>#3 Градиентный спуск - замораживание одного веса (влияние весов друг на друга)<b>

In [5]:
def neural_network(input, weights):
    out = 0
    for i in range(len(input)):
        out += (input[i] * weights[i])
    return out

def ele_mul(scalar, vector):
    out = [0] * 3
    for i in range(len(out)):
        out[i] = vector[i] * scalar
    return out

In [59]:
weights = [0.1, 0.2, -0.1]

toes = [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65, 0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]

win_or_lose_binary = [1, 1, 0, 1]

alpha = 0.3

true = win_or_lose_binary[0]
input = [toes[0], wlrec[0], nfans[0]]

In [60]:
for iter in range(3):
    
    pred = neural_network(input, weights)
    
    error = (pred-true) ** 2
    delta = pred - true
    
    weight_deltas = ele_mul(delta, input)
    weight_deltas[0] = 0
    
    print(f'Iteration: {iter}')
    print(f'Prediction: {pred}')
    print(f'Error: {error}')
    print(f'Delta: {delta}')
    print(f'Weights: {weights}')
    print(f'Delta Weights: \n{weight_deltas}')
    print("--------------------------" + "\n")
    
    for i in range(len(weights)):
        weights[i] -= alpha * weight_deltas[i]

Iteration: 0
Prediction: 0.8600000000000001
Error: 0.01959999999999997
Delta: -0.1399999999999999
Weights: [0.1, 0.2, -0.1]
Delta Weights: 
[0, -0.09099999999999994, -0.16799999999999987]
--------------------------

Iteration: 1
Prediction: 0.9382250000000001
Error: 0.003816150624999989
Delta: -0.06177499999999991
Weights: [0.1, 0.2273, -0.04960000000000005]
Delta Weights: 
[0, -0.040153749999999946, -0.07412999999999989]
--------------------------

Iteration: 2
Prediction: 0.97274178125
Error: 0.000743010489422852
Delta: -0.027258218750000007
Weights: [0.1, 0.239346125, -0.02736100000000008]
Delta Weights: 
[0, -0.017717842187500006, -0.032709862500000006]
--------------------------



<b>#4 Обучение метод градиентоного спуска с несколькими выходами<b>

In [9]:
def neural_network(input, weights):
    pred = ele_mul(input, weights)
    return pred

In [10]:
weights = [0.3, 0.2, 0.9]

wlrec = [0.65, 1.0, 1.0, 0.9]

hurt = [0.1, 0.0, 0.1]
win = [1, 1, 0, 1]
sad = [0.1, 0.0, 0.1, 0.2]

input = wlrec[0]
true = [hurt[0], win[0], sad[0]]

In [13]:
pred = neural_network(input, weights)

error = [0] * 3
delta = [0] * 3

for i in range(len(true)):
    error[i] = (pred[i] - true[i]) ** 2
    delta[i] = pred[i] - true[i]

weights_deltas = ele_mul(input, delta)
alpha = 0.1

for i in range(len(weights)):
    weights[i] -= weights_deltas[i] * alpha

print(f'Weights: {weights}')
print(f'Weights Deltas: {weights_deltas}')
print(neural_network(input, weights))

Weights: [0.28791089375, 0.3107107625, 0.83828193125]
Weights Deltas: [0.059141062499999994, -0.541607625, 0.3019306875]
[0.1871420809375, 0.20196199562500003, 0.5448832553125]


In [19]:
for iter in range(30):
    pred = neural_network(input, weights)

    error = [0] * 3
    delta = [0] * 3

    for i in range(len(true)):
        error[i] = (pred[i] - true[i]) ** 2
        delta[i] = pred[i] - true[i]

    weights_deltas = ele_mul(input, delta)
    alpha = 0.1

    for i in range(len(weights)):
        weights[i] -= weights_deltas[i] * alpha

    print(f'Weights: {weights}')
    print(f'Weights Deltas: {weights_deltas}')
    print(neural_network(input, weights))
    print("------------------\n")

Weights: [0.15958364855160814, 1.4859181658957996, 0.18313757418452556]
Weights Deltas: [0.0025310274216177905, -0.02317888270323636, 0.012921561047206527]
[0.1037293715585453, 0.9658468078322697, 0.11903942321994161]
------------------

Weights: [0.1593412394003027, 1.4881381233867021, 0.18190001167522934]
Weights Deltas: [0.0024240915130544377, -0.022199574909024678, 0.012375625092962044]
[0.10357180561019676, 0.9672897802013565, 0.11823500758889907]
------------------

Weights: [0.15910907203563993, 1.490264287673614, 0.1807147361819509]
Weights Deltas: [0.0023216736466278886, -0.021261642869118292, 0.011852754932784393]
[0.10342089682316595, 0.9686717869878492, 0.1174645785182681]
------------------

Weights: [0.15888671374213414, 1.492300621519404, 0.17957953857826348]
Weights Deltas: [0.002223582935057864, -0.02036333845789804, 0.011351976036874259]
[0.10327636393238719, 0.9699954039876125, 0.11672670007587126]
------------------

Weights: [0.15867375008652898, 1.494250920260209,

<b>#5 Обучение метод градиентоного спуска с несколькими выходами и несколькими входами<b>

In [52]:
def vect_mat_mul(vect, matrix):
    assert(len(vect) == len(matrix))
    output = [0] * 3
    
    for i in range(len(vect)):
        output[i] = w_sum(vect, matrix[i])
    return output

def neural_network(input, weights):
    pred = vect_mat_mul(input, weights)
    return pred

def outer_prod(vec_a, vec_b):
    out = np.zeros((len(vec_a), len(vec_b)))
    
    for i in range(len(vec_a)):
        for j in range(len(vec_b)):
            out[i][j] = vec_a[i] * vec_b[j]
    return out

In [59]:
    #игр, %победа, #болельщики
weights = [
    [0.1, 0.1, -0.3], #травмы
    [0.1, 0.2, 0.0], #победа
    [0.0, 1.3, 0.1] #печаль
]

#входные данные
toes = [8.5, 9.5, 9.9, 9.0,]
wlrec = [0.65, 0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]

#прогнозируемые
hurt = [0.1, 0.0, 0.0, 0.1]
win = [1, 1, 0, 1]
sad = [0.1, 0.0, 0.1, 0.2]

alpha = 0.001 #скорость обучения

input = [toes[0],wlrec[0], nfans[0]]
true = [hurt[0], win[0], sad[0]]

In [65]:
for i in range(25):
    pred = neural_network(input, weights)

    error = [0] * 3
    delta = [0] * 3

    for i in range(len(true)):
        error[i] = (pred[i] - true[i]) ** 2
        delta[i] = pred[i] - true[i]

    weight_deltas = outer_prod(input, delta)
    print(f'Weigths: {weights}')
    print(f'Weights deltas: {weight_deltas}\n')
    print(neural_network(input, weights))
    print("------------------------\n")
    
    for i in range(3):
        for j in range(3):
            weights[i][j] -= weight_deltas[i][j] * alpha

Weigths: [[0.09040135074697896, 0.12721098564535716, -0.7097451034239556], [0.09926598564535723, 0.20208084007876267, -0.03133344908536133], [-0.0013551034239559162, 1.3038415509146382, 0.04215363245779451]]
Weights deltas: [[-0.85506177 -0.53113708  6.6857854 ]
 [-0.06538708 -0.04061636  0.51126594]
 [-0.1207146  -0.07498406  0.94387559]]

[-0.0005955020899434116, 0.9375132851342985, 0.8865629879402429]
------------------------

Weigths: [[0.09125641251474348, 0.12774212272171562, -0.7164308888214477], [0.09933137272171569, 0.20212145644342538, -0.03184471502752249], [-0.0012343888214479842, 1.303916534972477, 0.04120975687226622]]
Weights deltas: [[-0.85854403 -0.53140337  6.68529378]
 [-0.06565337 -0.04063673  0.51122835]
 [-0.12120622 -0.07502165  0.94380618]]

[-0.001005180441302489, 0.9374819567897829, 0.8865051509965216]
------------------------

Weigths: [[0.09211495654849455, 0.12827352608900247, -0.7231161826049181], [0.09939702608900254, 0.20216209317151201, -0.0323559433756