<b>Библиотека Numpy<b>

In [2]:
import numpy as np

In [3]:
jeff_salary = [2700, 3000, 3000]
nick_salary = [2600, 2800, 2800]
tom_salary = [2300, 2500, 2500]

base_salary = np.array([jeff_salary, nick_salary, tom_salary])
base_salary

array([[2700, 3000, 3000],
       [2600, 2800, 2800],
       [2300, 2500, 2500]])

In [4]:
jeff_bonus = [500, 400, 400]
nick_bonus = [600, 300, 400]
tom_bonus = [600, 300, 400]

bonus = np.array([jeff_bonus, nick_bonus, tom_bonus])
bonus

array([[500, 400, 400],
       [600, 300, 400],
       [600, 300, 400]])

In [7]:
salary_bonus = base_salary + bonus
type(salary_bonus)
salary_bonus

array([[3200, 3400, 3400],
       [3200, 3100, 3200],
       [2900, 2800, 2900]])

<b>Статистические функции<b>

In [8]:
salary_bonus.max()

3400

In [10]:
#максимальное в каждой строке
np.amax(salary_bonus, axis=1)

array([3400, 3200, 2900])

In [12]:
#максимальное в каждом столбце
np.amax(salary_bonus, axis=0)

array([3200, 3400, 3400])

In [13]:
#среднее значение
np.average(base_salary)

2688.8888888888887

In [14]:
#медиана выборки - базовых зарплат сотрудников
np.median(base_salary)

2700.0

In [15]:
#средняя значение максимальных ежемесячных выплат среди сотрудников
np.average(np.amax(salary_bonus, axis=1))

3166.6666666666665

<b>Библиотека Numpy<b>

In [16]:
import pandas as pd

In [17]:
data = ['Jeff Russel', 'Jane Boorman', 'Tom Heints']
emps_names = pd.Series(data)
emps_names

0     Jeff Russel
1    Jane Boorman
2      Tom Heints
dtype: object

In [18]:
emps_names = pd.Series(data, index=[9001, 9002, 9003])
emps_names

9001     Jeff Russel
9002    Jane Boorman
9003      Tom Heints
dtype: object

Доступ к данным Series

In [19]:
emps_names[9001]

'Jeff Russel'

In [20]:
emps_names.loc[9001]

'Jeff Russel'

In [24]:
#получть доступ к элемента по позиции
emps_names.iloc[2]

'Tom Heints'

In [26]:
#полусить доступ к нескольким элементам по их индексам с помощью среза
emps_names.loc[9001:9002] # именно интервал [a, b]

9001     Jeff Russel
9002    Jane Boorman
dtype: object

Несколько серий могут быть объедины в датафрейм

In [29]:
data = ['jeff.russel', 'jane.boorman', 'tom.heints']
emps_emails = pd.Series(data, index=[9001, 9002, 9003], name='emails')
emps_names.name = 'names'
df = pd.concat([emps_names, emps_emails], axis=1)
df

names        emails
9001   Jeff Russel   jeff.russel
9002  Jane Boorman  jane.boorman
9003    Tom Heints    tom.heints

In [31]:
data_phones = ['+92394810248', '+321831012', '+5823052842']
emps_phones = pd.Series(data_phones, index=[9001, 9002, 9003], name = 'phones')
df = pd.concat([emps_emails, emps_phones, emps_names], axis=1)
df

emails        phones         names
9001   jeff.russel  +92394810248   Jeff Russel
9002  jane.boorman    +321831012  Jane Boorman
9003    tom.heints   +5823052842    Tom Heints